# Generated by Django 4.0.1 on 2024-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=30, null=True)),
                ('checkout', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('total', models.BigIntegerField(null=True)),
                ('paymented', models.BigIntegerField(null=True)),
                ('missing', models.BigIntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('date_completed', models.DateTimeField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
