# Generated by Django 4.0.1 on 2024-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_alter_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
