# Generated by Django 4.0.1 on 2024-03-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True),
        ),
    ]
