# Generated by Django 4.0.1 on 2024-04-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Submitted'), (2, 'Processed'), (3, 'Shipped'), (4, 'Paymented'), (5, 'Cancelled')], default=1)),
                ('note', models.TextField()),
                ('total', models.BigIntegerField(default=0)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.checkout')),
            ],
        ),
    ]
