# Generated by Django 4.0.1 on 2024-05-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_checkout_id_alter_orderitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
