# Generated by Django 4.0.1 on 2024-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.TextField(default=None, null=True),
        ),
    ]
